### ISSUE TITLE
第二种方式是否会比第一种效率高一些？

### ISSUE THREAD

**Issue by hiboyluo** [Ortonzhang/simple-code#1]

**Comment by Ortonzhang** [comment]
@hiboyluo  嗯嗯，对的，使用IntersectionObserver来实现是最合适的

**Comment by hiboyluo** [comment]
@Ortonzhang 使用image组件得lazy-load属性也可以实现懒加载吧，但是感觉没什么效果，不知道楼主是否用过。

**Comment by Ortonzhang** [comment]
@hiboyluo 刚才试了下，也是看不出什么效果来😅
