### ISSUE TITLE
异步获取循环出的数据会报Node ".item-0" is not found. Intersection observer will not trigger.

### ISSUE THREAD

**Issue by HelloGGX** [Ortonzhang/simple-code#4]

**Comment by Ortonzhang** [comment]
@HelloGGX 麻烦描述的详细点

**Comment by Lmangoxx** [comment]
@Ortonzhang 意思是如果数据是异步加载的话，.item-*的视图还没渲染出来，这个时候用IntersectionObserver监听，会提示.item-0没有找到，确实有这种问题，作者给的demo里，data数据是写死的，并不是异步获取的，所以并没有这种问题

**Comment by melyao** [comment]
我也是这个问题 怎么解决的？？？

**Comment by melyao** [comment]
@HelloGGX @Lmangoxx 把监听方法写在onshow里面就不报错了 可以试试
